config/routes.rb
Spree::Core::Engine.add_routes do

  resources :users, only: [], :path => 'account' do
	  resource :avatar, only: [:new, :edit, :update, :destroy]
  end

  namespace :admin, path: Spree.admin_path do
    resources :users, only: [] do
      resource :avatar, only: :destroy
    end
  end

end

app/models/spree/picture_ability.rb
module Spree
  class PictureAbility
    include CanCan::Ability

    def initialize(user)
      user ||= Spree.user_class.new    	
	  	can :picture, Spree.user_class, id: user.id
		end

  end
end

app/models/spree/user_decorator.rb
module Spree::UserDecorator
  def self.prepended(base)
    base.has_one_attached :avatar, dependent: :destroy
    base.validates :avatar, content_type: ['image/png', 'image/jpg', 'image/jpeg'], size: { less_than: 5.megabytes }
  end
end
Spree::User.prepend Spree::UserDecorator

app/controllers/spree/admin/avatars_controller.rb
module Spree
  module Admin
    class AvatarsController < Spree::Admin::BaseController
      before_action :load_user

      def destroy
        if @user.avatar.purge
          flash[:success] = Spree.t(:avatar_deleted)
        end
        redirect_back(fallback_location: spree.admin_path)
      end

      private

      def load_user
        @user = Spree.user_class.find_by_id(params[:user_id])
        unless @user
          flash[:error] = Spree.t(:user_not_found)
          redirect_to admin_path
        end
      end

    end
  end
end

app/controllers/spree/avatars_controller.rb
module Spree
  class AvatarsController < Spree::StoreController

    before_action :load_object, on: [:update, :delete]

    def update
      if @user.update(avatar_params)
        flash[:success] = Spree.t(:account_updated)
      elsif @user.errors[:avatar]
        flash[:error] = @user.errors[:avatar].join(". ")
      else
        flash[:error] = Spree.t(:user_avatar_error)
      end
      redirect_to spree.account_url
    end

    def destroy
      @user.avatar.purge
      redirect_to spree.account_url
    end

    private

    def avatar_params
      params.require(:user).permit(:avatar)
    end

    def load_object
      @user ||= spree_current_user
      authorize! params[:action].to_sym, @user
    end

  end
end

app/helpers/sss_avatar/frontend_helper_decorator.rb
Spree::FrontendHelper.class_eval do

  def gavatar_url(user)
    if user.avatar.attached?
      main_app.url_for(user.avatar)
    elsif ENV['RAILS_ENV'] == "development"
      "sss_avatar/mujer3.png"
    else 
      default_url = "http://yovendo.herokuapp.com/mujer3.png"     
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      "http://gravatar.com/avatar/#{gravatar_id}.png?d=#{CGI::escape(default_url)}"
    end
  end

end

app/views/frontend/account/users/show.html.erb
<% content_for :account_sidebar do %>
  <%= render partial: 'spree/account/shared/sidebar', locals: {current: :account} %>
<% end %>

<% content_for :account_title do %>
  <%= Spree.t(:account) %>
<% end %>

<div data-hook="account_summary" class="account-summary well">
  <dl id="user-info">
    <dt><%= Spree.t(:email) %></dt>
    <dd><%= @user.email %> (<%= link_to Spree.t(:edit), spree.edit_account_user_path %>)</dd>
    <br />
    <dt><%= Spree.t(:credit_balance, scope: [:store_credits])%></dt>
    <dd>
      <%= Spree::Money.new(spree_current_user.total_available_store_credit, currency: Spree::Config[:currency]) %>
    </dd>
  </dl>
</div>

<div data-hook="account_avatar" class="account-summary well">
  <dl>
    <dt><%= Spree.t(:avatar) %></dt>
    <dd><%#= image_tag "sss_gravatar/cruz.png", size: 128 %>
        <%= image_tag avatar_url(@user, 64), size: 128 %>
        (<%= link_to Spree.t(:edit), spree.edit_account_user_path %>)
      <%= link_to spree.edit_account_avatar_url(@user, avatar), class: "btn btn-primary btn-sm" do %>
        <span class="glyphicon glyphicon-pencil"></span>
      <% end if can? :edit, @product => Spree::Image %>

    </dd>
  </dl>
</div>

app/views/spree/admin/users/_avatar_thumb.html.erb
<td>
  	<% if user.avatar.attached? %>
		<%= image_tag main_app.url_for(user.avatar), width: "35px" %>
	<% else %>
		<%= inline_svg_tag "person.svg", size: "35px*35px" %>
	<% end %>
</td>

app/views/spree/admin/users/_form.html.erb
<div data-hook="admin_user_form_fields" class="row">
  <div class="col-12 col-md-6">
    <div class="text-center">
      <% if @user.avatar.attached? %>
        <%= image_tag(main_app.url_for(@user.avatar), size: 150) %>
        <%= link_to inline_svg_tag("garbage_2.svg"),
                    spree.admin_user_avatar_path(@user),
                    class: "ml-3",
                    method: "delete" %>
      <% else %>
        <%= inline_svg_tag("person.svg", size: "150px*150px") %>
      <%  end %>
    </div>

    <div data-hook="admin_user_form_roles" class="form-group">
      <strong><%= Spree.t(:roles) %></strong>
      <%= f.collection_check_boxes :spree_role_ids, Spree::Role.all, :id, :name do |role_form| %>
        <div class="checkbox">
          <%= role_form.label for: "user_spree_role_#{role_form.object.name}" do %>
            <%= role_form.check_box id: "user_spree_role_#{role_form.object.name}" %>
            <%= role_form.object.name %>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

  <div data-hook="admin_user_form_password_fields" class="col-12 col-md-6">
    <%= f.field_container :email, class: ['form-group'] do %>
      <%= f.label :email, Spree.t(:email) %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.error_message_on :email %>
    <% end %>

    <%= f.field_container :password, class: ['form-group'] do %>
      <%= f.label :password, Spree.t(:password) %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.error_message_on :password %>
    <% end %>

    <%= f.field_container :password_confirmation, class: ['form-group'] do %>
      <%= f.label :password_confirmation, Spree.t(:confirm_password) %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.error_message_on :password_confirmation %>
    <% end %>
  </div>
</div>

app/views/spree/avatars/edit.html.erb
<div class="container account-page">

  <h3 class="text-uppercase spree-mb-large spree-mt-large spree-header" >
    <%= Spree.t(:edit_avatar) %></h3>

  <div class="row">
    <div class="col-12 col-lg-6 text-center">
      <div class="mb-3">
        <%= Spree.t(:user_avatar) %>
      </div>
      <%= image_tag(main_app.url_for(@user.avatar), id: "js-user-avatar-preview", size: 256) %>
    </div>
    
    <div class="col-12 col-lg-6 d-flex align-items-center">
      <div class="w-100">
        <%= form_for @user, url: user_avatar_url, method: :put do |f| %>
          <div class="form-group">
            <%= f.label :avatar, Spree.t(:filename) %>
            <%= f.file_field :avatar, id: "js-user-avatar-file" %>
          </div>
          <%= f.submit Spree.t(:update), class: 'btn btn-block btn-primary spree-btn' %>
        <% end if can? :update, @user  %>
      </div>
    </div>
  </div>

</div>

app/views/spree/avatars/new.html.erb
<div class="container account-page">

  <h3 class="text-uppercase spree-mb-large spree-mt-large spree-header" >
    <%= Spree.t(:edit_avatar) %></h3>

  <div class="row">
    <div class="col-12 col-lg-6 text-center">
      <div class="mb-3">
        <%= Spree.t(:user_avatar) %>
      </div>
      <%= image_tag("person.svg", id: "js-user-avatar-preview", size: 256) %>
    </div>
    
    <div class="col-12 col-lg-6 d-flex align-items-center">
      <div class="w-100">
        <%= form_for @user, url: user_avatar_url do |f| %>
          <div class="form-group">
            <%= f.label :avatar, Spree.t(:filename) %>
            <%= f.file_field :avatar, id: "js-user-avatar-file" %>
          </div>
          <%= f.submit Spree.t(:create), class: 'btn btn-block btn-primary spree-btn' %>
        <% end if can? :update, @user  %>
      </div>
    </div>
  </div>

</div>

app/views/spree/users/_delete_avatar_popup.html.erb
<div class="mx-auto delete-avatar-popup">
  <div class="d-flex delete-avatar-popup-icon js-delete-avatar-popup-close-button">
    <%= inline_svg_tag "close.svg", class: "w-100 h-100" %>
  </div>

  <p class="delete-avatar-popup-header">
    <%= Spree.t("avatar_action_popup.delete_title") %>
  </p>

  <p class='delete-avatar-popup-text'>
    <%= Spree.t("avatar_action_popup.delete_text").html_safe %>
  </p>

  <div class="d-flex delete-avatar-popup-buttons">
    <div class="btn bg-light-background text-primary border-2 border-primary text-uppercase font-weight-bold delete-avatar-popup-button js-delete-avatar-popup-close-button"><%= Spree.t(:cancel) %></div>
    <a
      id="delete-avatar-popup-confirm"
      class="btn btn-primary text-uppercase font-weight-bold delete-avatar-popup-button"
      data-method="delete"
      rel="nofollow"
      href="#"
    >
      <%= Spree.t("avatar_action_popup.delete_button") %>
    </a>
  </div>
</div>

app/views/spree/users/_show_avatar.html.erb
<div data-hook="account-avatar">
  <div class="mb-3"><%= Spree.t(:user_avatar) %></div>
  <div>
    <% if @user.avatar.attached? %>
      <%= link_to image_tag(main_app.url_for(@user.avatar), size: 150), spree.edit_user_avatar_path(@user), class: "mx-3" %>
      <%= link_to inline_svg_tag("garbage_2.svg", class: "ml-2"), spree.user_avatar_path(@user), id: "js-delete-avatar", class: "avatar-link", remote: true %>
      <%= link_to inline_svg_tag("edit.svg", class: "ml-2"), spree.edit_user_avatar_path(@user), class: 'avatar-link' %>
    <% else %>
      <%= link_to inline_svg_tag("person.svg", class: "no-user-avatar", size: "150px*150px"), spree.new_user_avatar_path(@user), class: "avatar-link" %>
    <%  end %>
  </div>
</div>

<div id="delete-avatar-popup" class="delete-avatar-popup-dropdown hide-on-esc">
  <%= render 'spree/users/delete_avatar_popup' %>
</div>

app/views/spree/users/avatar.html.erb
<div class="container account-page">

  <h3 class="text-uppercase spree-mb-large spree-mt-large spree-header" >
    <%= Spree.t('edit_picture') %></h3>

  <div class="row">
    <div class="col-12 col-lg-6 d-block text-center">
      <div class="mb-3">
        <%= Spree.t(:user_avatar) %>
      </div>
      <% @user.avatar.attached? ? url = main_app.url_for(@user.avatar) : url = "spree_avatar/person.svg" %>
      <%= image_tag(url, id: "user-avatar-preview", size: 256) %>
    </div>
    
    <div class="col-12 col-lg-6">
      <div class="user-avatar-form">
        <%= form_for @user, url: user_avatar_url, method: :put do |f| %>
          <div class="form-group">
            <%= f.label :avatar, Spree.t(:filename) %>
            <%= f.file_field :avatar, id: "user-avatar-file" %>
          </div>
          <%= f.submit Spree.t(:update), class: 'btn btn-primary btn-block spree-btn mb-5' %>
        <% end if can? :avatar, @user  %>
      </div>
    </div>
  </div>

</div>

app/views/spree/users/avatar_show.html.erb
<div class="col-xs-12 col-lg-4" data-hook="account-avatar">
  <% if @user.avatar.attached?
      url = main_app.url_for(@user.avatar)
      image = image_tag(url, size: 150)
    else
      url = "spree_avatar/person.svg"
      image = inline_svg_tag(url, class: "no-user-avatar", size: "150px*150px")
    end %>
  <div class="d-block text-center mb-3">
    <%= Spree.t(:user_avatar) %>
  </div>
  <div class="text-center">
    <%= link_to image, spree.user_avatar_path(@user), class: "edit-avatar-link" %>
    <%= link_to inline_svg_tag('edit.svg'), spree.user_avatar_path(@user), class: "edit-avatar-link" %>
    <% if @user.avatar.attached? %>
      <div class="delete-avatar-button js-delete-avatar-button" data-avatar="<%= spree.user_delete_avatar_path(@user) %>">
        <%= inline_svg_tag 'garbage_2.svg' %>
      </div>
    <% end %>
  </div>
</div>

<div id="delete-avatar-popup" class="delete-address-popup-dropdown hide-on-esc">
  <%= render 'spree/shared/delete_avatar_popup' %>
</div>

app/views/spree/users/edit_avatar.html.erb
<div class="container account-page">

  <h3 class="text-uppercase spree-mb-large spree-mt-large spree-header" >
    <%= Spree.t('edit_picture') %></h3>

  <div class="row">
    <div class="col-12 col-lg-6 d-block text-center">
      <div class="mb-3">
        <%= Spree.t(:user_avatar) %>
      </div>
      <% @user.avatar.attached? ? url = main_app.url_for(@user.avatar) : url = "spree_avatar/person.svg" %>
      <%= image_tag(url, id: "user-avatar-preview", size: 256) %>
    </div>
    
    <div class="col-12 col-lg-6">
      <div class="user-avatar-form">
        <%= form_for @user, url: user_update_avatar_url, method: :put do |f| %>
          <div class="form-group">
            <%= f.label :avatar, Spree.t(:filename) %>
            <%= f.file_field :avatar, id: "user-avatar-file" %>
          </div>
          <%= f.submit Spree.t(:update), class: 'btn btn-primary btn-block spree-btn mb-5' %>
        <% end if can? :update_avatar, @user  %>
      </div>
    </div>
  </div>

</div>

app/views/spree/users/picture.html.erb
<div class="container account-page">

  <h3 class="text-uppercase spree-mb-large spree-mt-large spree-header" >
    <%= Spree.t('edit_picture') %></h3>

  <div class="row">
    <div class="col-12 col-lg-6 d-block text-center">
      <div class="mb-3">
        <%= Spree.t(:user_picture) %>
      </div>
      <% @user.picture.attached? ? url = main_app.url_for(@user.picture) : url = "isell_avatar/person.svg" %>
      <%= image_tag(url, id: "user-picture-preview", size: 256) %>
    </div>
    
    <div class="col-12 col-lg-6">
      <div class="user-picture-form">
        <%= form_for @user, url: user_picture_url, method: :put do |f| %>
          <div class="form-group">
            <%= f.label :picture, Spree.t(:filename) %>
            <%= f.file_field :picture, id: "user-picture-file" %>
          </div>
          <%= f.submit Spree.t(:update), class: 'btn btn-primary btn-block spree-btn mb-5' %>
        <% end if can? :picture, @user  %>
      </div>
    </div>
  </div>

</div>